#端口，项目上下文根
server:
  port: 8081
  servlet:
    context-path: /


#配置mybatis
mybatis-plus:
  #配置xml映射路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰命名法
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置mysql连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/canteen?serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  #文件大小 MB必须大写
  #  maxFileSize 是单个文件大小
  #  maxRequestSize是设置总上传的数据大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 200MB

#mybatis-plus:
#    #配置实体类的别名
#  type-aliases-package: com.ct.entity
#  configuration:
##  #开启驼峰命名法
#  #map-underscore-to-camel-case: true
#  # 日志
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  #配置xml映射路径
#  mapper-locations: "classpath*:/mapper/*Mapper.xml"

